function CreateBoxplotBoys(XData1, YData1, YData2, XData2, YData3, YData4, XData3, YData5, XData4, YData6, XData5, YData7)
%CREATEFIGURE(XData1, YData1, YData2, XData2, YData3, YData4, XData3, YData5, XData4, YData6, XData5, YData7)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata
%  XDATA2:  line xdata
%  YDATA3:  line ydata
%  YDATA4:  line ydata
%  XDATA3:  line xdata
%  YDATA5:  line ydata
%  XDATA4:  line xdata
%  YDATA6:  line ydata
%  XDATA5:  line xdata
%  YDATA7:  line ydata

%  Auto-generated by MATLAB on 04-Feb-2018 00:03:47

% Create figure
figure1 = figure('Name','Boxplot - Boys');

% Create axes
axes1 = axes('Parent',figure1);

% Create hggroup
hggroup1 = hggroup('Parent',axes1,'Tag','boxplot');

% Create line
line(XData1,YData1,'Parent',hggroup1,'Tag','Upper Whisker','LineStyle','--');

% Create line
line(XData1,YData2,'Parent',hggroup1,'Tag','Lower Whisker','LineStyle','--');

% Create line
line(XData2,YData3,'Parent',hggroup1,'Tag','Upper Adjacent Value');

% Create line
line(XData2,YData4,'Parent',hggroup1,'Tag','Lower Adjacent Value');

% Create line
line(XData3,YData5,'Parent',hggroup1,'Tag','Box','Color',[0 0 1]);

% Create line
line(XData4,YData6,'Parent',hggroup1,'Tag','Median','Color',[1 0 0]);

% Create line
line(XData5,YData7,'Parent',hggroup1,'Tag','Outliers',...
    'MarkerEdgeColor',[1 0 0],...
    'Marker','+',...
    'LineStyle','none');

% Create title
title({'Boxplot of Check Form Distribution - Boys'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[15966.55 16218.45]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'TickLabelInterpreter','none','XTick',1,'XTickLabel',{'1'});
