function CreateBarChartGirls(yvector1)
%CREATEFIGURE(yvector1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 03-Feb-2018 23:57:41

% Create figure
figure1 = figure('Name','Check Form Distribution - Girls');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar(yvector1);

% Create ylabel
ylabel({'Check Form Usage Count'},'HorizontalAlignment','center');

% Create xlabel
xlabel({'Check Form IDs'},'HorizontalAlignment','center');

% Create title
title({'Check Form Distribution - Girls'});

box(axes1,'on');
