function CreateHistogramBoys(data1)
%CREATEFIGURE(data1)
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 04-Feb-2018 09:12:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create histogram
histogram(data1,'Parent',axes1,'BinMethod','auto');

% Create ylabel
ylabel({'Check Form Distribution'});

% Create title
title({'Histogram of Check Distribution - Boys'});

box(axes1,'on');
